### ISSUE TITLE
Contributions file

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/pyemoodji#2]

**Comment by rachelywong** [comment]
''Milestone1 says "Once the projects have been created, edit CONTRIBUTORS.md to add the contributor names (the students on the teams)." However, there is no CONTRIBUTORS.md generated by the cookiecutter template. Instead, there is now a Contributors section in the README, you can put the contributor names there."

The contributions file has been changed to add the info into the READme instead:

## Contributors
This repository is currently maintained by [Rachel](https://github.com/rachelywong), [Aidan](https://github.com/aidanmattrick), [Yiki](https://github.com/YikiSu), and [Kevin](https://github.com/kshahnazari1998).
