### ISSUE TITLE
Test functions

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/pyemoodji#26]
Please write a test function for each functions.

- [x] sentiment_df
- [x] sentiment_plot
- [x] counter
- [x] emoji_replacement

**Comment by rachelywong** [comment]
```This week, show us a smile (yours or someone else's), make us smile, or both. Share a photo of something that has brought a moment of joy into your life recently, or focus on the outcome of that joy. If you're not feeling particularly cheerful at the moment — it's still 2018, after all — no need to fake your way into the challenge, either. Smiles come in all shades and flavors, including the half-hearted, tired, bitter, and resigned (to name a few). So whether the emotions you channel in your photo are full of cheer or not, I can't wait to see your take on this theme.```

test text file
