### ISSUE TITLE
R project structure

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/pyemoodji#28]
- [x] Create R repo (remoodji)
- [x] Add team members to DESCRIPTION file
- [x] Code of Conduct
- [x] Contributing file
- [x] README
- [x] Each function needs documentation like last time
- [ ] Add branch protection @Kevin Shahnazari for python repo and @Aidan Mattrick for R repo

**Comment by rachelywong** [comment]
for the README we'll have to change the current packages that exist from the python ones to the R ones like `tidytext`
