### ISSUE TITLE
unit test for sentiment analysis functions

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/pyemoodji#29]
df function:
- [x] test the input, must be string
- [x] test the input for sentiment should be in the sentiment list
- [x] test the output, must be dataframe
- [x] test the output dataframe should have 5 columns
- [x] test some random values for the word_count, the emotion_percentage

plot function:
- [x] test the input, must be string
- [x] test the input for sentiment should be in the sentiment list
- [x] test the output, must be plot
- [x] test the output axis should be word_count vs word
- [x] test the output plot should bar graph

**Comment by rachelywong** [comment]
plot function:

- [x] width and height are integers

**Comment by YikiSu** [comment]
- [ ] integration test
- [ ] boost up the coverage
