### ISSUE TITLE
READme

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/pyemoodji#4]
- [x] Rachel sends the function notes to Aidan
- [x] Aidan drafts the READme 
- [x] Rachel peer reviews the file

**Comment by rachelywong** [comment]
## README notes:

### Summary paragraph

- a text analysis package that focuses on sentiment analysis in text files
- used for determining what kind of underlying emotion your input text gives off and quantitative analyses of your text (word/sentence/character count, sentiment analysis quantification in dataframe and plot)
- important for proof reading messages or texts where you want to elicit a certain emotion or tone (speeches, letters, applications, cover letters? lol)
- emotions analyzed include angry, happy, sad, disgust
- emoji replacement of words to convert your text file to a text file where you can physically see the emotion
- provides visualizations of your input text depending on what the user wants to see (top 10 happy words used or top 10 sad words used etc.)

### Functions

Counter:
- input: textfile(s?)
- output: dataframe with word count, sentence count, and character count

Sentiment Analysis Dataframe: 
- input: textfile(s?)
- output: dataframe with sentiment analysis (sentiment_type, sentiment_words, percentage of sentiment? like sentiment_words/total_words), and highest sentiment % (what emotion the text shows the most)?

Character Replacement:
- input: textfile(s?), parameter for which words to replace (happy, sad, angry, etc.)
- takes in information from sentiment analysis function (does it need to take in the dataframe as input?)
- output: textfile with words replaced with emojis

Sentiment Analysis Plot:
- input: dataframe from sentiment analysis function, parameter for what the user wants to see
- output: plot
- shows some sort of visualization of like top 10 happy words or top 10 words overall based on user input

### Where your packages fit into the Python ecosystem
- tidytext (R) and nltk (python) already exist but we are adding emojis to it and further analyzing text data to provide more quantitative sentiment analysis (word/sentence/character count as well as sentiment count and %)
- we also add visualizations (adding emojis to text showcase the emotion from the words itself, a plot showing the sentiment analysis shows the top words found in the text)

**Comment by rachelywong** [comment]
''Milestone1 says "Once the projects have been created, edit CONTRIBUTORS.md to add the contributor names (the students on the teams)." However, there is no CONTRIBUTORS.md generated by the cookiecutter template. Instead, there is now a Contributors section in the README, you can put the contributor names there." - Tiff

The contributions file has been changed to add the info into the READme instead:

## Contributors
This repository is currently maintained by [Rachel](https://github.com/rachelywong), [Aidan](https://github.com/aidanmattrick), [Yiki](https://github.com/YikiSu), and [Kevin](https://github.com/kshahnazari1998).
