### ISSUE TITLE
Functions 

### ISSUE THREAD

**Issue by YikiSu** [UBC-MDS/pyemoodji#9]
- [x] counter - Aidan
- [x] sentiment analysis for dataframe - Yiki and Rachel
- [x] sentiment analysis for plot - Yiki and Rachel
- [x] sentiment analysis for emojis - Kevin

**Comment by rachelywong** [comment]
potential ideas for counter function:

- count punctuation too? exclamation marks = emotion
- count emojis if they exist?
- rank by character count? (longest word to shortest word)
